import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif_Georgian } from "next/font/google"; // Import Noto Serif Georgian
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerifGeorgian = Noto_Serif_Georgian({
  variable: "--font-noto-serif-georgian", // Add variable for Noto Serif Georgian
  subsets: ["georgian"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSerifGeorgian.variable} font-vintage antialiased`} // Include Noto Serif Georgian variable
      >
        {children}
      </body>
    </html>
  );
}
